### ISSUE TITLE
Script and Document docker-machine workflow

### ISSUE THREAD

**Issue by discorick** [huboard/huboard-cache#14]
Using docker-machine in tandem with `docker-compose` gets as far as configuring a VM for both containers (postgres and cache) to run on. Unfortunately the docker-machine does not automatically forward ports on the host.

A variety of different solutions are presented here: http://stackoverflow.com/questions/32174560/port-forwarding-in-docker-machine, none of them seem fantastic.

**Comment by drusellers** [comment]
> Unfortunately the docker-machine does not automatically forward ports on the host

I'm not sure I follow. The ports are forwarded as stated in the spec here: https://github.com/huboard/huboard-cache/blob/master/docker-compose.yml#L6

**Comment by discorick** [comment]
Yes, so from `docker-container` -> `docker-machine`, the port forward seems to work just fine. From `docker-machine` -> `osx` is where I _suspect_ the problem is.

**Comment by drusellers** [comment]
But why would you ever use docker-machine by itself?

**Comment by discorick** [comment]
After wiping the machine and starting fresh things are working... strange.
